package com.hamilton.healthi;

import android.content.Context;
import android.os.AsyncTask;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.sqlite.db.SupportSQLiteDatabase;

@Database(entities = AllNote.class, version = 1, exportSchema = false)
public abstract class AllNoteDatabase extends RoomDatabase {

    private static AllNoteDatabase allInstance;

    public abstract AllNoteDao allNoteDao();

    public static synchronized AllNoteDatabase getInstance(Context context) {
        if (allInstance == null) {
            allInstance = Room.databaseBuilder(context.getApplicationContext(),
                    AllNoteDatabase.class, "All_Note_Database")
                    .fallbackToDestructiveMigration()
                    .addCallback(allRoomCallback)
                    .build();
        }
        return allInstance;
    }

    private static RoomDatabase.Callback allRoomCallback = new RoomDatabase.Callback() {
        @Override
        public void onCreate(@NonNull SupportSQLiteDatabase db) {
            super.onCreate(db);
            new PopulateDbAsyncTask(allInstance).execute();
        }
    };

    private static class PopulateDbAsyncTask extends AsyncTask<Void, Void, Void> {
        private AllNoteDao allNoteDao;

        private PopulateDbAsyncTask(AllNoteDatabase db) {
            allNoteDao = db.allNoteDao();
        }

        @Override
        protected Void doInBackground(Void... voids) {
            allNoteDao.allInsert(new AllNote("ADHD", "Attention deficit hyperactivity disorder usually begins in childhood but often is not diagnosed until adolescence or adulthood. Some risk factors include genetics, low birth weight, brain injuries, and alcohol or tobacco use during pregnancy. Symptoms of ADHD include inattention, difficulty focusing, difficulty following directions, hyperactivity, impatience, and acting without thinking. Doctors commonly treat this with medications such as stimulants and antidepressants, psychotherapy, and education."));
            allNoteDao.allInsert(new AllNote("Alopecia", "Alopecia is the medical term for losing hair or going bald. Some risk factors include having a family history of baldness, being treated for cancer, harsh hair treatments, menopause, and having a major illness or surgery. Treatment depends on what is causing your hair loss and may include hair implants, taking certain medications, changing your prescription or reducing the dosage if medication is causing your hair loss, making dietary changes or other lifestyle changes, and treating an overactive or underactive thyroid."));
            allNoteDao.allInsert(new AllNote("Alzheimer's", "Alzheimer's is a type of dementia that causes connections between neurons in the brain to break down and eventually die. Risk factors include old age, a family history of Alzheimer's, having certain genes, being female, a serious head injury, and having fewer than eight years of education. Some symptoms include trouble with short-term memory, confusion, changes in behavior, not recognizing loved ones, problems making decisions, and trouble swallowing, talking, and walking. Treatments include taking certain medications, vitamin E, and antidepressants."));
            allNoteDao.allInsert(new AllNote("Arthritis", "Doctors don't know what triggers the autoimmune response that cause arthritis, but the condition is more common in women than men. Some symptoms include joint pain, swelling, fever, fatigue, swollen glands, weight loss, morning stiffness, and red hands. Treatments may include taking medications that suppress the immune system or are anti-inflammatory, corticosteroids, physical therapy, and sometimes surgery."));
            allNoteDao.allInsert(new AllNote("Asthma", "Some risk factors for asthma include having allergies, having a family history of asthma or allergies, having eczema, or being obese. Symptoms of asthma may include wheezing, chest tightness or pain, shortness of breath, and cough. Symptoms of a severe asthma attack may include blue lips, difficulty speaking, confusion, extreme difficulty breathing, sweating, and anxiety. Treatments may include taking certain medications, and allergy treatment, if your asthma is triggered by allergies."));
            allNoteDao.allInsert(new AllNote("Bipolar Disorder", "Risk factors for bipolar disorder includes having a family history of it, substance abuse, stress, trauma, not getting enough sleep, thyroid problems, and steroids that may trigger a mood swing. Symptoms may include low self-esteem, suicidal thoughts, changes in appetite, withdrawal from friends and family, loss of interests in things you enjoy, increased energy, decreased need for sleep, irritability, and insomnia. Treatments may include taking medications called mood stabilizers, taking antidepressants, and sometimes electroconvulsive therapy."));
            allNoteDao.allInsert(new AllNote("Borderline Personality Disorder", "BPD is a serious mental illness. There's no known cause, but it's believed to be a combination of the way your brain in built and the things you experience in life. Symptoms may include having antisocial or compulsive behavior, having emotional instability, being insecure, feeling worthless, and having impaired social relationships. Treatments may include going to talk therapy or in some cases, taking certain medications."));
            allNoteDao.allInsert(new AllNote("Brain Tumor", "Risk factors for brain tumors may include being older, previous radiation exposure, and inheriting conditions that affect the brain. Symptoms vary depending on the type of tumor and where it is in the brain. Symptoms may include seizures, muscle twitches and weakness, changes in thinking, difficulty speaking or understanding speech, personality changes, dizziness, ongoing headaches, changes in hearing, taste, smell, or sensation, and eye or vision changes. Treatments may include radiation therapy, chemotherapy, surgery, and taking certain medications to help with symptoms."));
            allNoteDao.allInsert(new AllNote("Bronchitis", "Cold viruses are the most common cause of bronchitis, but it can also be caused by bacteria. Smoking, air pollution, asthma, and dehydration make this condition worse. Symptoms of this illness include cough, dark or yellow mucus, wheezing, chest pain, and shortness of breath. Treatments may include rest, drinking plenty of fluids, breathing in warm, moist air, over-the-counter pain relievers, and medications to help reduce coughing and open your airways."));
            allNoteDao.allInsert(new AllNote("Cancer", "Cancer can cause almost any type of sign or symptom. Some of the most common signs and symptoms of cancer include weight loss, fever, tiredness, a lump or other changes in the skin, pain, cough, indigestion, unusual bleeding, changes in the mouth, swollen lymph nodes, being out of breath, bloating, and anemia. Some treatments of cancer may include surgery, chemotherapy, and radiation therapy."));
            allNoteDao.allInsert(new AllNote("Carpal Tunnel Syndrome", "Repetitive movement from computer work, factory work, or anything that stresses the wrist and forearms can lead to carpal tunnel syndrome. Symptoms may include burning or tingling in the hand and fingers, numbness, wrist or hand pain, wrist joint stiffness, wrist weakness, weak grip, and trouble making small finger movements. Treatments may include resting, taking anti-inflammatory medications, exercising your hand and wrist, wrist splints, having cortisone injections, and sometimes surgery."));
            allNoteDao.allInsert(new AllNote("Celiac Disease", "Celiac disease is caused by a reaction to gluten, a protein found in wheat, rye, and barley. It tends to run in families, but can also occur in people without a family history of the disease. Symptoms may include nausea, tiredness, hair loss, anemia, depression, joint pain, skin rash, and weight loss. The only treatment for celiac disease is a gluten-free diet."));
            allNoteDao.allInsert(new AllNote("Chickenpox", "Chickenpox is very contagious, but the chickenpox vaccine has greatly reduced the number of cases. Symptoms may include having a blistering rash, swollen lymph nodes, fever and chills, loss of appetite, headaches, and sore throat. In most people, chickenpox usually clears up in about five to seven days without any treatment. If you are at risk for complications, your doctor may give you an antiviral medication to help reduce your symptoms."));
            allNoteDao.allInsert(new AllNote("Chronic Obstructive Pulmonary Disease", "Smoking is the most common cause of COPD. It often takes many years to develop. Some symptoms include shortness of breath, tiredness, weakness, a chronic cough, difficulty exercising, wheezing, chest tightness, and turning blue with exertion. Some risk factors are smoking, having been exposed to secondhand smoke, being over age 40, and being exposed to fumes, dust, or air pollution. Treatments may include quitting smoking, medications to open airways, oxygen, pulmonary rehabilitation, and sometimes surgery."));
            allNoteDao.allInsert(new AllNote("Cirrhosis", "Cirrhosis is a long term liver disease. The leading causes are excessive alcoholism and chronic hepatitis C virus infection. Many people have no symptoms in the early stages. As it progressives, symptoms may include tiredness, loss of appetite, nausea and vomiting, abdominal pain and bloating, yellowish skin, itching, enlarged tips of the fingers, and unusual bruising and bleeding. Cirrhosis can't be cured, but it is possible to prevent further damage to the liver. This includes stopping drinking and avoiding medications that may be toxic to the liver."));
            allNoteDao.allInsert(new AllNote("Common Cold", "Colds spread easily from person to person and are the most common illness in the world. Symptoms of a common cold may include throat pain and sensitivity, sneezing, runny or stuffy nose, low-grade fever, headache, muscle aches, cough, and tiredness. Colds usually get better on their own in a few days. Antihistamines, decongestants, pain relievers, drinking plenty of fluids, and breathing in steam may help ease symptoms."));
            allNoteDao.allInsert(new AllNote("Coronary Artery Disease", "This condition is caused by a buildup of plaque in your coronary arteries. Early symptoms may include chest pain during exercise, shortness of breath, pain in the jaw, arm, or back, heart palpitations, weakness, dizziness, and irregular heartbeat. Treatments for this condition include eating a healthy diet, getting more exercise, losing weight if needed, medications to control blood pressure, and sometimes surgery to bypass the blocked arteries."));
            allNoteDao.allInsert(new AllNote("Coronavirus", "Coronavirus came from China and is very contagious. On average, it takes five to six days from when someone is infected with the virus for symptoms to show, however it can take up to fourteen days. Symptoms may include having a fever, dry cough, tiredness, aches and pains, nasal congestion, runny nose, and sore throat. There are no specific vaccines or medications for coronavirus. Self care treatments include resting, drinking plenty of fluids, maintaining a healthy diet, and self-isolation."));
            allNoteDao.allInsert(new AllNote("Dandruff", "Dandruff is a common condition, although it is not contagious. Some risk factors include having oily skin and hair, having a medical condition, recovering from a heart attack, and having a compromised immune system. A symptom of dandruff is having loose, white flakes of skin that may itch appearing on your scalp. Treatments may include taking prescriptions or over-the-counter dandruff shampoos, topical corticosteroids, and steroid-containing shampoos."));
            allNoteDao.allInsert(new AllNote("Dementia in Head Injury", "People who have a serious head injury can develop dementia. Some people with dementia after a head injury get better over months and years. Others don't. Symptoms may include memory loss, difficulty reasoning or concentrating, speech problems, emotional problems, impulsiveness, irritability or aggression, personality changes, difficulty sleeping, coordination problems, headaches, tiredness, depression, and anxiety. Treatments may include rehabilitation with different therapists and taking certain medications to treat symptoms."));
            allNoteDao.allInsert(new AllNote("Depression", "Many people feel down for short periods, but depression lasts a long time. Life events such as the death of a loved one can trigger depression. Some symptoms may include a lack of enjoyment in previously enjoyed activities, hopelessness, anxiety, nervousness, insomnia, excess sleeping, frustration, decreased or increased appetite, lack of motivation, and suicidal thoughts. Depression treatments may include antidepressant medication, counseling, and electroconvulsive therapy for severe depression and if some antidepressants don't work."));
            allNoteDao.allInsert(new AllNote("Diabetes, Type 2", "Type 2 diabetes occurs when the body does not make enough insulin or does not use it as it should. Being overweight increases your risk for type 2 diabetes, but not everyone who is overweight will develop the illness. Some symptoms include fatigue, increased appetite, slow-healing or frequent infections, excess thirst, and blurry vision. Some treatments for diabetes include going on a diet, getting more exercise, losing weight if needed, taking oral medications, and taking insulin."));
            allNoteDao.allInsert(new AllNote("Ear Infection", "Children and teenagers who spend a lot of time at the pool in the summer are especially prone to ear infections. Symptoms may include having ear pain or itching, decreased hearing, feeling as though the ear is plugged, flaking skin, and drainage from the ear. Treatments may include using antibacterial eardrops mixed with a steroid to reduce swelling, taking antibiotics, taking ibuprofen, and using a warm towel to help relieve pain."));
            allNoteDao.allInsert(new AllNote("Epilepsy", "Epilepsy is a condition marked by seizures. Risk factors include having a severe infection, head injury, having a family history of it, oxygen deprivation, brain infections, stroke, Alzheimer's, and brain tumors. Symptoms can vary from monetary confusion to violent convulsions. Two out of three cases of epilepsy have no known cause. If no cause is discovered, your doctor may prescribe an oral medication to help prevent seizures. In some cases, brain surgery can be performed to remove a small part of the brain that may be causing certain kinds of seizures."));
            allNoteDao.allInsert(new AllNote("Eye Allergies", "Pollen, dust mites, mold, pet dander, and other allergens can trigger a reaction in the clear layer over the eye, called the conjunctiva. Eye allergy symptoms include red, itchy, burning, and watery eyes. Your eyelids may be puffy and your vision blurry. Treatments include avoiding allergens, taking antihistamines and decongestants, and in some cases, allergy shots to reduce the body's response to the allergen."));
            allNoteDao.allInsert(new AllNote("Flu", "The flu is a respiratory tract infection caused by the influenza virus, and spreads easily from person to person. Flu symptoms include fever, sore throat, runny nose, headache, cough, muscle aches, and tiredness. The flu usually gets better on its own in one to two weeks with rest. Antihistamines, decongestants, pain relievers, drinking plenty of fluids, and inhaling steam may help ease symptoms. For people at risk for complications and those with severe symptoms, antiviral medications may help reduce the duration of symptoms and prevent complications if they are taken soon after symptoms appear."));
            allNoteDao.allInsert(new AllNote("Gingivitis", "Gingivitis is a mild form of gum disease caused mainly by poor oral hygiene. Some other causes are having a family history, smoking, having diabetes, and taking certain medications. Symptoms may include redness and swelling of the gums. Treatments may include having a dentist remove sticky plaque on teeth, and they may suggest medication to help control bacteria levels in your mouth."));
            allNoteDao.allInsert(new AllNote("Hypertension (High Blood Pressure)", "In most cases, there's no one cause of high blood pressure. It often happens with age. Other risk factors are being overweight, having a family history, heavy drinking, lack of exercise, and poor diet. Most people who have high blood pressure don't have any symptoms, you can have it for years and not know it. In more severe cases, it can cause headaches, shortness of breath, nosebleeds, and extreme anxiety. You may be able to lower blood pressure by going on a diet, limiting daily salt intake, exercising daily, managing stress, and quitting smoking."));
            allNoteDao.allInsert(new AllNote("Insomnia", "Insomnia is the inability to get to sleep or stay asleep at night. Drinking alcohol or caffeine, stress, medications, an uncomfortable sleep environment, and work schedule changes can lead to short-term insomnia. Chronic insomnia often results from mental health problems and can be a sign of depression. Symptoms may include difficulty concentrating, lack of energy, moodiness, anxiety, irritability, and depression. Improving your sleep habits often takes care of short-term insomnia. Other treatments may include treating any underlying health problem and taking prescription sleeping pills."));
            allNoteDao.allInsert(new AllNote("Kidney Stones", "You are at risk for kidney stones if you have a family history of it, have had one already, don't drink enough water, eat foods with too much salt or sugar, have had certain infections, surgeries, or taken certain medications. Symptoms may include sudden, severe, and continuing pain on either side of the lower back, nausea, fever, and chills. Treatments for this condition include drinking plenty of water, taking pain medications and antibiotics, lifestyle changes to prevent recurrence, and sometimes surgery."));
            allNoteDao.allInsert(new AllNote("Lumbar Strain", "Lumbar strains and sprains are the most common causes of lower back pain. People may get them from picking up something heavy, industrial work, or sports that require lifting, pushing, or twisting. Some symptoms include stiffness, pain when touching the area, and muscle spasms. Treatments may include bed rest for a few days, ibuprofen for pain and swelling, ice packs, having an ultrasound, physical therapy, and taking certain medications such as muscle relaxants."));
            allNoteDao.allInsert(new AllNote("Malaria", "Malaria is a dangerous disease spread by mosquitoes. In rare cases, it's spread by blood transfusions. Symptoms may include fever, chills, headaches, sweating, anemia, muscle pain, body ache, yellow skin, seizures, breathing problems, kidney failure, and in severe cases, coma. Treatments may include taking medications to fight the infection, IV fluids, and being hospitalized."));
            allNoteDao.allInsert(new AllNote("Migraine", "Migraines are a common type of headache that can cause severe pain. They can last for a few hours or a few days. Symptoms include having a dull or severe headache that may be worse on one side of the head, and a throbbing, pulsating, or pounding in the head. Other symptoms may include loss of appetite, nausea, sensitivity to sound or light, chills, sweating, and numbness or tingling. Severe migraines are usually treated with prescription medications."));
            allNoteDao.allInsert(new AllNote("Osteoporosis", "Osteoporosis occurs when bones become weak and can break more easily. The first symptom of osteoporosis is often a fractured bone. Other signs include a loss of weight or abnormal curvature of the upper back. Treatments may include eating healthy with a focus on fruits and vegetables, exercising daily, having a strategy to prevent you from falling, and taking medications to prevent bone loss."));
            allNoteDao.allInsert(new AllNote("Pneumonia", "This condition is commonly caused by bacteria or viruses. Some risk factors include old age, living in a nursing home, smoking, having a recent cold or flu, having asthma, having a weak immune system, and having recent surgery or injury. Symptoms may include cough, chest pain, headache, sore throat, shortness of breath, wheezing, fever, chills, confusion, and tiredness. Treatments may include antibiotics, antiviral therapy, oxygen, and steroids."));
            allNoteDao.allInsert(new AllNote("Psoriasis", "Psoriasis is a common genetic condition that occurs when skin cells grow too quickly and pile up on the surface of the skin. It may look contagious, but it isn't. Symptoms may include having red, white, or silvery raised patches of scaly skin that may appear anywhere on the body, and having dry, flaky, cracked skin that may bleed. Treatments may include using moisturizers, using corticosteroid creams, phototherapy, and injections of biologic drugs, which target specific parts of the immune system."));
            allNoteDao.allInsert(new AllNote("Schizophrenia", "Schizophrenia is a serious, chronic, mental illness. Symptoms may include hearing voices, hallucinations, paranoia, delusions, thought disorder, lack of emotion, anxiety, difficulty sleeping, irritability, confusion, memory problems, suicidal thoughts, and social withdrawal. Treatments may include taking antipsychotic or antidepressant medications, counseling, and social skills training."));
            allNoteDao.allInsert(new AllNote("Scoliosis", "Scoliosis occurs when the spine curves sideways more than it should. Doctors don't know what causes most cases of scoliosis. Symptoms may include having uneven shoulders or hip, prominent shoulder blades, leaning to one side, back pain, and tiredness. Severe scoliosis can cause breathing problems. Treatments may include using a back brace and having surgery. Scoliosis is made worse by growth spurts and chronic wheelchair use."));
            allNoteDao.allInsert(new AllNote("Strep Throat", "Strep throat is a throat infection caused by streptococcal bacteria. Symptoms include red throat, white patches on throat, throat pain, trouble swallowing, swollen lymph glands, nausea, fever, chills, muscle aches, stomach aches, rash, and headache. Strep throat should be treated with antibiotics to shorten the illness, prevent potentially serious complications, and also make it less contagious after 48 hours of treatment. Self-cares for this illness include gargling with warm salt water, over-the-counter pain relievers, drinking plenty of fluids, rest, and not smoking."));
            allNoteDao.allInsert(new AllNote("Tuberculosis", "Tuberculosis spreads when an infected person coughs, sneezes, speaks, or sings, which releases droplets into the air that other people can breath in. If not treated, the illness can be serious and even fatal. Symptoms may include a bad cough, coughing up blood, chest pain, night sweats, fever, chills, fatigue, loss of appetite, and weight loss. Treatments include taking certain medications for 6 months to a year to kill bacteria. It's very important to take your medication exactly as directed."));

            return null;
        }
    }
}
